### ISSUE TITLE
我找不到合适版本的caffe，有哪位好心人告诉我下嘛？

### ISSUE THREAD

**Issue by oujieww** [shicai/Caffe_Manual#7]
我按照shicai说的找了个有vision_layers的caffe但是缺少别的一些东西不能用，但是新版的caffe又没有vision_layer所以，有没有人可以发我一份caffe-master，希望能帮助我下。也可以直接发到我邮箱965728310@qq.com嘻嘻嘻，突然发现把DenseNet的问题提到这里来了

**Comment by shicai** [comment]
没关系的，以前的老版本中vision layers已经拆分到其他几个layers的头文件中了，ceil_mode你可以加到pooling的头文件中，参考：https://github.com/BVLC/caffe/blob/master/include/caffe/layers/pooling_layer.hpp
